# Site settings
title: Dr Steven Daviss
twitter_username: HITshrink
name: Steve Daviss

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Home Page
   url: https://drdaviss.com
 - title: GitHub
   url: https://github.com/sdaviss
 - title: Something
   url: nothing.to.see.here
 - title: Old Blogger Site
   url: https://hitshrink.blogspot.com
 - title: LinkedIn
   url: https://www.linkedin.com/in/drdaviss

#Any buzzword skills you want to include
skills:
 - Medicine
 - Psychiatry
 - Clinical informatics
 - Addiction medicine
 - Primary care
 - Data science
 - Integrated care
 - Policy
 - Standards
 - CoCM
 - Parity
 - HIT
 - 42CFRPart2
 - SAMHSA
 - CCHIT
 - EHR
 - HIE
 - ASAM
 - AMIA
 - APA
 - Interoperabiliy
 - Privacy
 - Measurement-based care
 - Analyst
 - CRISP
 - Photography
 - Python
 - Sonic-Pi
 - Markdown 
 - Clinical algorithms
 - CDS
 

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: 

#Work experience is required
roles:
 - title: Optum - UnitedHealth Group
   start: 2019
   end: Ongoing
   employer: Medical Director
   description: Maryland Medicaid ASO for behavioral health (half-time now)
 - title: Mindoula Health
   start: 2018
   end: 2019
   employer: Lead Psychiatrist
   description: Collaborative care psychiatrist, worked on CoCM care teams, product dev, BD support, data analysis, clinical algorithms, clinical SME
 - title: SAMHSA/DHHS
   start: 2017
   end: 2018
   employer: Senior Medical Advisor - Medical Director
   description: Office of the Chief Medical Officer (OCMO) & Center for Substance Abuse Treatment (CSAT)
 - title: M3 Information
   start: 2013
   end: 2017
   employer: CMIO
   description: chief medical informatics officer; platform design; workflow devpt; product devpt; business devpt; strategy; quality mgmt
 - title: AbsoluteCare
   start: 2014
   end: 2015
   employer: Collaborative Care Psychiatrist
   description: unique integrated care setting collaborating with primary care teams
- title: Founding President/CEO
   start: 2013
   end: 2019
   employer: Fuse Health Strategies
   description: consultant with expertise at the intersection of psychiatry, primary care, technology, informatics, health policy, standards
 - title: Univ of Maryland Baltimore Washington Medical Center 
   start: 2004
   end: 2013
   employer: Psychiatry Dept Chairman
   description: lead 12 psychiatrists & $6M department in growth, quality improvement, outcomes, financial performance, reputation
   

#Education is required
education:
 - level: Doctor of Medicine
   date: 1989
#  subject: Artificial Intelligence and Computer Science
   school: University of Maryland School of Medicine
 - level: Residency in Psychiatry
   date: 1993
   school: University of Pittsburgh Medical Center
 - level: Fellowship in Clinical Research
   date: 1995
   school: Maryland Psychiatric Research Center

#This section is optional (as is the image link below)
#coursera:
#   profileurl: 
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018

#List of interesting Github repo/projects to include - optional
# github:
# - sdaviss/opioids

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: 
#   flairimageurl: 

intro: |
  Steve Daviss, MD, DFAPA, DABPM, is a Maryland-based physician triple-boarded in Psychiatry, Addiction Medicine, and Psychosomatic Medicine, with expertise in the intersection of psychiatry, primary care, health information technology, data science, and healthcare policy. Dr. Daviss is the incoming president of ASAM's Maryland-D.C. chapter, past president of the Maryland Psychiatric Society (MPS), and is medical director for Optum Maryland, which manages the Maryland Medicaid contract for specialty behavioral health services.
  He recently served in other leadership positions, including founding president and CEO of Fuse Health Strategies and lead psychiatrist for Mindoula Health’s Collaborative Care Program. He formerly served as HHS Senior Medical Advisor to the Office of the Chief Medical Officer and Medical Director of the Center for Substance Abuse Treatment at SAMHSA, where he focused on addiction and mental health policy matters. He served on a number of related task forces and councils, including the HHS Pain Management Task Force, CDC/HRSA Advisory Committee on HIV and Hepatitis, and the Federal Health IT Coordinating Council. Prior to beginning his service to HHS, he served in numerous leadership positions in clinical, medical informatics, and healthcare policy areas, including clinical assistant professor of Psychiatry at University of Maryland, chair of the Department of Psychiatry at University of Maryland Baltimore Washington Medical Center, Chief Medical Informatics Officer at M3 Information, chair of the Parity Accreditation Committee of ClearHealth Quality Institute, and election to Recorder of the Assembly at the American Psychiatric Association in 2017. 
  Other past advocacy and leadership roles include chair of the APA Committee on Mental Health Information Technology, chair of the Public Policy Committee and Board of Directors member for the Maryland-DC Society of Addiction Medicine, and APA Assembly Representative for MPS for eight years. In Maryland, he has served on the Health Care Commission’s Health Information Exchange Policy Board, Health Services and Cost Review Commission’s Performance Measurement committee, and Medicaid Pharmacy & Therapeutics Committee. Work on national standards organizations include URAC’s Health Standards Committee for ten years (currently on URAC's Accreditation Committee) and co-chair of CCHIT’s Workgroup on Behavioral Health Electronic Health Records, where he co-led a multidisciplinary two-year effort to produce nationally-accepted standards for behavioral health EHRs. 
  Dr. Daviss is co-author of the 2011 book from Johns Hopkins University Press, “Shrink Rap: Three Psychiatrists Explain Their Work,” and produced the successful podcast, "My Three Shrinks." He is @HITshrink on Twitter.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Stuff</strong>: stuff here, links, etc
   <strong>More stuff</strong>: other stuff too
